/* eslint-disable */


export default {
    pageLoading: true,
    pageProcessing: false,
    actionProcessing: false,
    status: false,
    token: sessionStorage.getItem('appUserThemeSettingsCode') || '',
    isUserAdmin: sessionStorage.getItem('draggerability') || '',
    user: null,
    currentSitePage: '/',
    userAmount: 520,
    makePayment: false,
    logoutModal: false,
    appId: null,
    // userId: null,
    // emailToken: null,
    notifications: [],
    registrationText: false,
    countries: [],
    isUserLoggedIn: false,
    // userExpireLoginTime: null,
    AppId: '001',
    RequestId: Math.floor(Math.random()),
    addWorkHistoryModal: false,
    addschoolHistoryModal: false,
    addCertificationModal: false,
    addGuarantorModal: false,
    addRefereeModal: false,
    selectPaymentOptionModal: false,
    bankTransferModal: false,
    debitCreditCardModal: false,
    uploadEvidienceModal: false,
    UploadEvidenceFormModal: false,
    addBvnModal: false,
    PaymentFormModal: false,
    commingSoonModal: false,
    guarantorModal: false,
    registrationInfo: null,
    alertStatus: false,
    alertType: '',
    alertMessage: '',
    currentpayment: null,
    userPaymentOptions: null,
    clickedPaymentType: null,
    userBankDetails: null,
    emailConfirmModal: false,
    countryBankName: [],
    hrmURL: "http://api.oxfordhrmportal.com/api",
    walletURL: "http://walletgateway.oxfordvest.com/api",

    // Payments
    amount: 0,
    currency: "",
    processing: false,
    buttonText: "Proceed",
    emptyFields: true,
    inputError: false,
    formError: false,
    payWithPaystack: false,
    payWithRave: false,
    paymentForPaystackInfo: null,
    paymentForRaveInfo: null,
    errorMessage: "",
    showError: false,

};